// Real MV3 + isolated Edge, synthetic X and model responses. No real model claim.
const { chromium } = require('./load-playwright.cjs').loadPlaywright();
const assert = require('node:assert/strict');
const fs = require('node:fs');
const os = require('node:os');
const path = require('node:path');
(async()=>{
  const root=path.resolve(process.env.EXTENSION_ROOT || path.join(__dirname,'..'));
  const profile=fs.mkdtempSync(path.join(os.tmpdir(),'bx-agent-'));
  let context;
  try {
    context=await chromium.launchPersistentContext(profile,{channel:'msedge',headless:true,args:[`--disable-extensions-except=${root}`,`--load-extension=${root}`]});
    context.setDefaultTimeout(10000);
    const worker=context.serviceWorkers()[0] || await context.waitForEvent('serviceworker');
    const extensionId=new URL(worker.url()).host;
    const manager=await context.newPage();
    await manager.goto('edge://extensions');
    // Headless Edge has no clickable native permission bubble. Grant the test host
    // through Edge's extension manager, then verify the real permissions API.
    await manager.evaluate(id=>chrome.developerPrivate.addHostPermission(id,'http://127.0.0.1/*'),extensionId);
    await manager.close();
    await worker.evaluate(()=>{
      globalThis.__agentCalls=[];
      globalThis.fetch=async(url,options={})=>{
        const body=options.body?JSON.parse(options.body):null;
        globalThis.__agentCalls.push({url:String(url),body,redirect:options.redirect});
        if(String(url).endsWith('/api/tags'))return Response.json({models:[{name:'qwen3:8b'}]});
        if(String(url).endsWith('/api/chat'))return Response.json({message:{content:'# Agent draft\n\nCareful answer.'}});
        if(String(url).endsWith('/session'))return Response.json({id:'smoke-session'});
        if(String(url).endsWith('/message'))return Response.json({parts:[{type:'text',text:'OpenCode careful answer'}]});
        if(String(url).endsWith('/global/health'))return Response.json({healthy:true,version:'fixture'});
        return Response.json({});
      };
    });
    const errors=[];
    context.on('page',p=>p.on('pageerror',e=>errors.push(e.message)));
    const settings=await context.newPage();
    await settings.goto(`chrome-extension://${extensionId}/options.html`);
    await settings.locator('#agent-base-url').fill('http://127.0.0.1:11434');
    await settings.locator('#auto-translate').uncheck();
    await settings.locator('#save-main').click();
    await settings.waitForFunction(()=>document.querySelector('#status').textContent.includes('已保存'));
    await settings.locator('#test-agent').click();
    await settings.waitForFunction(()=>document.querySelector('#agent-connection').textContent.includes('Ollama ·')).catch(async e=>{throw new Error(e.message+'; '+await settings.locator('#agent-connection').innerText());});
    assert.equal(await worker.evaluate(()=>chrome.permissions.contains({origins:['http://127.0.0.1/*']})),true);
    console.log('PASS settings save and real host permission (granted by Edge extension manager)');
    const desk=await context.newPage();
    await desk.goto(`chrome-extension://${extensionId}/write/desk.html`);
    await desk.waitForFunction(()=>document.body.dataset.ready==='1');
    await desk.locator('#markdown-editor').fill('# Local title\n\n<img src=x onerror=alert(1)>');
    await desk.locator('[data-view="split"]').click();
    assert.equal(await desk.locator('#markdown-preview img').count(),0);
    await desk.locator('#context-document').check();
    await desk.locator('#agent-prompt').fill('Make a careful draft');
    await desk.locator('#agent-send').click();
    await desk.locator('#agent-output-actions').waitFor();
    await desk.locator('[data-apply="append"]').click();
    await desk.waitForFunction(()=>document.querySelector('#save-state').textContent==='已保存');
    await desk.reload();
    await desk.waitForFunction(()=>document.body.dataset.ready==='1');
    assert.match(await desk.locator('#markdown-editor').inputValue(),/Careful answer/);
    assert.match(await desk.locator('#agent-thread').innerText(),/Make a careful draft/);
    console.log('PASS Markdown escape, apply, save and reload with Agent history');
    const x=await context.newPage();
    await x.route('https://x.com/agent-fixture',route=>route.fulfill({contentType:'text/html',body:'<main>'+[1,2].map(id=>`<article id="p${id}" data-testid="tweet"><div data-testid="tweetText">POST_${id} explicit source text.</div><a href="/writer/status/${id}">post</a><div role="group"></div></article>`).join('')+'</main>'}));
    await x.goto('https://x.com/agent-fixture');
    await x.locator('#p1 .bx-entry-reply').click();
    await x.locator('[data-bx-mode="agent"]').click();
    await x.locator('#bx-agent-prompt').fill('Draft a reply');
    await x.locator('[data-agent-context="post"]').check();
    await x.locator('#bx-agent-send').click();
    await x.locator('#bx-agent-use').waitFor();
    await x.locator('#bx-agent-use').click();
    assert.match(await x.locator('#bx-draft').inputValue(),/Careful answer/);
    await x.locator('#p2 .bx-entry-reply').click();
    await x.locator('[data-bx-mode="agent"]').click();
    assert.equal(await x.locator('#bx-agent-use').count(),0);
    console.log('PASS X Agent explicit context, manual adoption and post isolation');
    await settings.locator('#agent-provider').selectOption('opencode');
    await settings.locator('#save-main').click();
    await settings.waitForFunction(()=>document.querySelector('#status').textContent.includes('已保存'));
    await settings.locator('#test-agent').click();
    await settings.waitForFunction(()=>document.querySelector('#agent-connection').textContent.includes('OpenCode'));
    await desk.locator('#agent-prompt').fill('Revise using OpenCode');
    await desk.locator('#agent-send').click();
    await desk.waitForFunction(()=>document.querySelector('#agent-thread').textContent.includes('OpenCode careful answer'));
    const requests=await worker.evaluate(()=>globalThis.__agentCalls);
    const chat=requests.find(r=>r.url.endsWith('/message'));
    assert.deepEqual(chat.body.tools,{'*':false});
    assert.equal(chat.redirect,'error');
    assert(requests.some(r=>r.url.endsWith('/api/chat') && r.body.messages.at(-1).content.includes('POST_1')));
    const backup=await settings.evaluate(()=>chrome.runtime.sendMessage({action:'BACKUP',payload:{op:'export'}}));
    assert(backup.ok && Object.keys(backup.data.storage.documents).length);
    assert(!JSON.stringify(backup.data).includes('smoke-session'));
    assert.deepEqual(errors,[]);
    console.log('PASS OpenCode tools disabled and backup excludes remote session IDs');
    console.log('AGENT_SMOKE_PASS (real extension; model network fixtures, not live services)');
  } finally {if(context)await context.close();fs.rmSync(profile,{recursive:true,force:true});}
})().catch(e=>{console.error(e);process.exitCode=1;});
